import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import { Toaster } from "react-hot-toast";
import TokenContextProvider from "@/components/Provider/TokenProvider";
import dotenv from "dotenv";

dotenv.config();
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TokenContextProvider>
          <Toaster position="top-right" reverseOrder={false} />
          <Navbar />
          <div>{children}</div>
          <Footer />
        </TokenContextProvider>
      </body>
    </html>
  );
}
